apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expenseowl-pvc
  namespace: expenseowl
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
